In [1]:
import numpy as np #kısaltma olarak istediğimizi genellikle np yazılır

# numpy array

In [2]:
my_list = [10,20,30,40]
type(my_list)

list

In [3]:
np.array(my_list)

array([10, 20, 30, 40])

In [4]:
my_numpy_array = np.array(my_list)

In [5]:
type(my_numpy_array)

numpy.ndarray

In [6]:
my_numpy_array

array([10, 20, 30, 40])

In [7]:
my_numpy_array[0]

10

In [8]:
my_numpy_array[-1]

40

In [9]:
my_numpy_array[0] = 100

In [10]:
my_numpy_array

array([100,  20,  30,  40])

In [11]:
my_numpy_array.max() #maximum değer

100

In [12]:
my_numpy_array.mean() #ortalamasını alır

47.5

In [13]:
matrix_list =[[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [14]:
numpy_matrix_list = np.array(matrix_list)

In [15]:
numpy_matrix_list.shape #(a,b) a:satır b:kolon

(4, 3)

# arrange

In [16]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,30,2) #0'dan 30'a ikişer yazdırır

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [19]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# linspace

In [21]:
np.linspace(0,10,100) #0'dan 10'a virgülsen sonra 100 arttırarak

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# random

In [22]:
np.random.randint(1,10,3) #1den 10a kadar rastgele 3 değer al

array([2, 3, 3])

# numpy arrays methods

In [23]:
your_numpy_list = np.arange(0,20)
your_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
your_numpy_list[4:9:2]

array([4, 6, 8])

In [25]:
your_list = list(range(0,20))
your_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [26]:
your_list[4:9:2]

[4, 6, 8]

In [27]:
#your_list[4:9] = -10 çalışmaz

In [28]:
your_numpy_list[4:9] = -10

In [29]:
other_list = np.arange(0,15)

In [30]:
slicing_list = other_list[4:10]

In [31]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [32]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
your_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [34]:
slicing_my_list = your_list[4:9]

In [35]:
slicing_my_list[1] = -100
slicing_my_list[0] = -100

In [36]:
slicing_my_list

[-100, -100, 6, 7, 8]

In [37]:
numpy_list = np.arange(0,20)

In [38]:
numpy_list_copy = numpy_list.copy()

In [39]:
numpy_list_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
slicing_1 = numpy_list_copy[4:9]

In [41]:
slicing_1[:] = -100

In [42]:
slicing_1

array([-100, -100, -100, -100, -100])

In [43]:
numpy_list_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [44]:
numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# numpy operation with numpy arrays

In [45]:
new_array = np.random.randint(1,150,25)

In [46]:
new_array

array([ 37,  23,  43, 109,  52, 135,  35, 136,  40,  83,  95, 109,  33,
       115,  52, 101,  37, 142,  89, 128, 140,  89,  28,  76,  76])

In [47]:
new_array > 50

array([False, False, False,  True,  True,  True, False,  True, False,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True])

In [48]:
result_array = new_array > 50

In [49]:
result_array

array([False, False, False,  True,  True,  True, False,  True, False,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True])

In [50]:
new_array

array([ 37,  23,  43, 109,  52, 135,  35, 136,  40,  83,  95, 109,  33,
       115,  52, 101,  37, 142,  89, 128, 140,  89,  28,  76,  76])

In [51]:
new_array[result_array] #true olanları gösterir

array([109,  52, 135, 136,  83,  95, 109, 115,  52, 101, 142,  89, 128,
       140,  89,  76,  76])

In [52]:
last_array = np.arange(0,30)

In [53]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [54]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [55]:
last_array.max()

29

In [56]:
np.max(last_array)

29

In [57]:
np.mean(last_array)

14.5

In [58]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])